<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\Warzone.glb -T --draco /draco/
-->

<script lang="ts">
  import { T } from "@threlte/core";
  import { useGltf, useDraco, FakeGlowMaterial   } from "@threlte/extras";
  import { AutoColliders, Collider } from "@threlte/rapier";
  import { handleJump } from "../../utils/utils";

  let {
    fallback = () => {},
    error = () => {},
    children = () => {},
    ref = $bindable(),
    ...props
  } = $props();

  const gltf = useGltf("/Warzone-transformed.glb", { dracoLoader: useDraco() });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Circle007.geometry}
      material={gltf.materials["Material.058"]}
      position={[-54.64, 0.18, -2.06]}
      scale={11.66}
    />

    <AutoColliders shape="convexHull" oncollisionenter={handleJump}>
      <T.Mesh
        geometry={gltf.nodes.Circle007.geometry}
        material={gltf.materials["Material.058"]}
        position={[-54.64, 0.18, -2.06]}
        scale={11.66}
      />
    </AutoColliders>

    <AutoColliders shape="cuboid" oncollisionenter={handleJump}>
      <T.Mesh
        geometry={gltf.nodes.Puente.geometry}
        material={gltf.materials["Material.030"]}
        position={[-37.81, -0.07, -0.29]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.2, 0.5, 0.2]}
      />
    </AutoColliders>

    <T.Group position={[-38.04, 0.81, 0.53]}>
      <Collider shape="cuboid" args={[0.2, 0.5, 0.2]}>
        <T.Mesh
          geometry={gltf.nodes.Palo002.geometry}
          material={gltf.materials["Material.035"]}
          scale={[0.2, 2, 0.2]}
        />
      </Collider>
    </T.Group>
    <AutoColliders shape="convexHull" oncollisionenter={handleJump}>
      <T.Mesh
        geometry={gltf.nodes.Rock1.geometry}
        material={gltf.materials["Material.034"]}
        position={[-57.3, -0.18, 6.88]}
        rotation={[0, -1.29, 0]}
        scale={1.2}
      />
      <T.Mesh
        geometry={gltf.nodes.Rock2.geometry}
        material={gltf.materials["Material.034"]}
        position={[-51.55, -0.18, -10.23]}
        rotation={[0, 0.16, 0]}
        scale={1.2}
      />
    </AutoColliders>

    <T.Group position={[-43.28, 1, -1.3]}>
      <Collider shape="cuboid" args={[0.2, 2, 0.2]}>
        <T.Mesh
          geometry={gltf.nodes.Palo003.geometry}
          material={gltf.materials["Material.035"]}
          scale={[0.2, 2, 0.2]}
          position={[0, 0, -0.26]}
        />
      </Collider>
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Palo.geometry}
      material={gltf.materials["Material.035"]}
      position={[-28.64, 3.54, -0.04]}
      rotation={[-Math.PI, 1.52, -Math.PI]}
      scale={[1, 4, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo001.geometry}
      material={gltf.materials["Material.035"]}
      position={[-30.47, 2.58, -0.63]}
      rotation={[Math.PI, -1.49, Math.PI]}
      scale={[0.83, 3.33, 0.83]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube025.geometry}
      material={gltf.materials["Material.057"]}
      position={[-27.96, 4.05, -0.68]}
      rotation={[0, 1.56, 0]}
      scale={[1.5, 0.4, 0.1]}
    />

    <T.Mesh
      geometry={gltf.nodes.Curve.geometry}
      position={[-27.8, 4.03, -0.68]}
      rotation={[Math.PI / 2, 0, -1.56]}
      scale={2.74}
    >
      <FakeGlowMaterial
        glowColor={"darkred"}
        falloff={1}
        glowInternalRadius={5}
        glowSharpness={1}
        depthTest={true}
      />
    </T.Mesh>
    <T.Mesh
      geometry={gltf.nodes.Curve004.geometry}
      material={gltf.materials["Material.049"]}
      position={[-56.89, 0.17, 8]}
      rotation={[0.45, -0.47, 2.95]}
      scale={12.75}
    />
    <T.Group
      position={[-54.33, 1.45, -2]}
      rotation={[Math.PI / 2, 0, -2.63]}
      scale={4}
    >
      <Collider shape="cuboid" args={[0.14, 0.25, 0.19]} oncollisionenter={handleJump}>
        <T.Mesh
          geometry={gltf.nodes.Cofre_1.geometry}
          material={gltf.materials["SVGMat.018"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cofre_2.geometry}
          material={gltf.materials["FrontColor.003"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cofre_3.geometry}
          material={gltf.materials["Material.056"]}
        />
      </Collider>
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cylinder032.geometry}
      material={gltf.materials["Material.046"]}
      position={[-59.01, 4.39, -3.49]}
      rotation={[0, 0.55, 0]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder033.geometry}
      material={gltf.materials["Material.046"]}
      position={[-57.92, 2.99, -0.8]}
      rotation={[-2.88, 1.52, -3.03]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder034.geometry}
      material={gltf.materials["Material.046"]}
      position={[-56.38, 2.99, -4.54]}
      rotation={[-3.12, -0.83, -2.75]}
      scale={4.1}
    />
    <AutoColliders shape="convexHull">
      <T.Mesh
        geometry={gltf.nodes.RockaGrande.geometry}
        material={gltf.materials["Material.052"]}
        position={[-62.85, 4.07, -5.62]}
        rotation={[-Math.PI, 1.54, -Math.PI]}
        scale={[1.32, 3.96, 1.32]}
      />
      <T.Mesh
        geometry={gltf.nodes.RockaMediana.geometry}
        material={gltf.materials["Material.052"]}
        position={[-62.21, 1.96, -0.61]}
        rotation={[-2.61, 1.54, Math.PI]}
        scale={[0.88, 2.64, 0.88]}
      />
      <T.Mesh
        geometry={gltf.nodes.RockaMediana001.geometry}
        material={gltf.materials["Material.052"]}
        position={[-59.69, 1.9, -8.52]}
        rotation={[-2.81, 1.53, 2.27]}
        scale={[0.88, 2.64, 0.88]}
      />
    </AutoColliders>
    <T.Group position={[-58.12, 0.27, 5.56]} scale={[1.4, 2, 1.4]}>
      <Collider shape="cuboid" args={[0.45, 0.35, 0.45]} oncollisionenter={handleJump}>
        <T.Mesh
          geometry={gltf.nodes.Barril1_1.geometry}
          material={gltf.materials["Material.054"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Barril1_2.geometry}
          material={gltf.materials["Material.055"]}
        />
      </Collider>
    </T.Group>
    <T.Group
      position={[-50.57, 0.18, 2.58]}
      rotation={[-1.52, 0, 0]}
      scale={[1.4, 2, 1.4]}
    >
      <Collider shape="cuboid" args={[0.45, 0.35, 0.45]} oncollisionenter={handleJump}>
        <T.Mesh
          geometry={gltf.nodes.Barril1_1.geometry}
          material={gltf.materials["Material.054"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Barril1_2.geometry}
          material={gltf.materials["Material.055"]}
        />
      </Collider>
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Plane024.geometry}
      material={gltf.materials["Material.047"]}
      position={[-57.48, 5.49, 3.06]}
      rotation={[-2.76, -0.84, -3.13]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane025.geometry}
      material={gltf.materials["Material.047"]}
      position={[-50.82, -0.27, 6.34]}
      rotation={[3.09, -0.5, 3]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane026.geometry}
      material={gltf.materials["Material.047"]}
      position={[-59.98, 8.14, -2.28]}
      rotation={[-Math.PI, 0.24, -Math.PI]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane028.geometry}
      material={gltf.materials["Material.047"]}
      position={[-54.91, 5.95, -6.89]}
      rotation={[-0.25, 0.08, -0.26]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane027.geometry}
      material={gltf.materials["Material.047"]}
      position={[-57.28, 5.95, 1.9]}
      rotation={[-2.76, -0.84, -3.13]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane029.geometry}
      material={gltf.materials["Material.047"]}
      position={[-49.89, -0.23, 5.88]}
      rotation={[0.7, -1.5, 0.58]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane030.geometry}
      material={gltf.materials["Material.047"]}
      position={[-49.44, -0.22, 4.85]}
      rotation={[0.07, -0.81, -0.07]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane031.geometry}
      material={gltf.materials["Material.047"]}
      position={[-46.77, -0.27, -5.96]}
      rotation={[2.81, -1.43, 2.69]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane032.geometry}
      material={gltf.materials["Material.047"]}
      position={[-46.58, -0.23, -6.97]}
      rotation={[0.06, -0.58, -0.09]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane033.geometry}
      material={gltf.materials["Material.047"]}
      position={[-47.15, -0.22, -7.95]}
      rotation={[0.05, 0.13, -0.12]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Group position={[-63.88, 11.08, -5.97]}>
      <T.PointLight
        color="red"
        distance={4}
        intensity={10}
        power={1000}
        position={[0, 0, 0]}
      />

      <T.Mesh
        geometry={gltf.nodes.Calabera.geometry}
        material={gltf.materials["Material.053"]}
        rotation={[0, 1.16, 0]}
        scale={15.36}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
