<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\spacestation.glb -T --draco /draco\
-->

<script lang="ts">
  import { type RigidBody as RapierRigidBody } from "@dimforge/rapier3d-compat";
  import { T, useTask } from "@threlte/core";
  import { FakeGlowMaterial, HTML, useDraco, useGltf } from "@threlte/extras";
  import { AutoColliders, Collider, RigidBody } from "@threlte/rapier";
  import { Group } from "three";
  import { keys } from "../../../stores/keyStores";
  import { handleJump } from "../../utils/utils";
  import Flames from "./Flames.svelte";

  let {
    webSocket,
    fallback = () => {},
    error = () => {},
    children = () => {},
    ref = $bindable(),
    ...props
  } = $props();

  const gltf = useGltf("/spacestation-transformed.glb", {
    dracoLoader: useDraco(),
  });

  let spaceShip = $state<any | null>(null);
  let rigidBody: RapierRigidBody | undefined = $state<RapierRigidBody>();
  let flamesRef: Group | undefined = $state<Group>();
  let flameTargetX = $state(0);

  let currentColor = $state({ h: 180, s: 100, l: 50 }); // Cyan inicial en HSL
  let colorInterval = $state<any>();
  let isOnCheckPoint = $state(false);

  const handleTakeOffEvent = () => {
    isOnCheckPoint = true;
  };

  function lerp(a: number, b: number, t: number) {
    return a + (b - a) * t;
  }

  webSocket.messages.subscribe((message: any) => {
    if (!message?.type) return;
    switch (message.type) {
      case "spaceShip": {
        spaceShip = message.spaceShip;
        // console.log(spaceShip);
        break;
      }

      case "spaceShipUpdate": {
        // spaceShip.position = message.position;
        rigidBody?.setTranslation(message.position, true);
        // rigidBody?.applyTorqueImpulse({ x: 0, y: 1000, z: 0 }, true);
        break;
      }

      case "turnOnFlames": {
        if (flamesRef) {
          flameTargetX = message.flames ? -6 : 0;
        }
        break;
      }
    }
  });

  $effect(() => {
    // window.addEventListener("keydown", handleKeyDown);

    colorInterval = setInterval(() => {
      currentColor.h = (currentColor.h + 60) % 360; // Cambia el tono cada 2 segundos
    }, 2000);
    return () => {
      // window.removeEventListener("keydown", handleKeyDown);
      clearInterval(colorInterval);
    };
  });

  useTask(() => {
    if (!flamesRef) return;

    // console.log(spaceShip);

    flamesRef.position.y = lerp(flamesRef.position.y, flameTargetX, 0.1);

    if (Math.abs(flamesRef.position.y - flameTargetX) < 0.01) {
      flamesRef.position.y = flameTargetX;
    }

    if (isOnCheckPoint && $keys.e.isPressed && spaceShip && !spaceShip.status) {
      // console.log("take off");
      webSocket.send({
        type: "turnOnSpaceship",
        id: spaceShip.id,
      });
    }
  });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    {#if spaceShip}
      <T.Group
        position={[
          spaceShip.position.x,
          spaceShip.position.y,
          spaceShip.position.z,
        ]}
      >
        <RigidBody
          bind:rigidBody
          enabledRotations={[false, true, false]}
          type="kinematicPosition"
        >
          <Collider shape="cuboid" args={[2, 4.5, 2]}>
            <T.Group position={[0, 1.5, 0]} scale={[1, 5, 1]}>
              <T.Mesh
                geometry={gltf.nodes.SpaceShip005.geometry}
                material={gltf.materials["Material.020"]}
              />
              <T.Mesh
                geometry={gltf.nodes.SpaceShip005_1.geometry}
                material={gltf.materials["Material.021"]}
              />
              <T.Mesh
                geometry={gltf.nodes.SpaceShip005_2.geometry}
                material={gltf.materials["Material.021"]}
              />
            </T.Group>
          </Collider>
          <Flames bind:flamesRef />
        </RigidBody>
      </T.Group>
    {/if}

    <!-- Space Station -->
    <AutoColliders shape="trimesh" oncollisionenter={handleJump}>
      <T.Group position={[56.45, 2.51, -41.68]} rotation={[Math.PI / 2, 0, 0]}>
        <T.Mesh
          geometry={gltf.nodes.Station_1.geometry}
          material={gltf.materials.FrontColor}
        />
        <T.Mesh
          geometry={gltf.nodes.Station_2.geometry}
          material={gltf.materials["Material.006"]}
        />
      </T.Group>
    </AutoColliders>

    <T.Group position={[48, 5.01, -45.8]} scale={[2, 5, 1]}>
      <AutoColliders shape="cuboid">
        <T.Mesh
          geometry={gltf.nodes.Base_1.geometry}
          material={gltf.materials["Material.023"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Base_2.geometry}
          material={gltf.materials["Material.022"]}
        />
      </AutoColliders>
    </T.Group>

    <!-- Space Station -->

    <!-- Sensor -->
    <T.Group>
      <AutoColliders
        shape="cuboid"
        sensor={true}
        onsensorenter={handleTakeOffEvent}
        onsensorexit={() => (isOnCheckPoint = false)}
      >
        <T.Mesh position={[55.69, 3.3, -40.19]}>
          <T.CylinderGeometry args={[0.4, 0.4, 0.5]} />
          <FakeGlowMaterial
            glowColor="green"
            falloff={1}
            glowInternalRadius={1}
            glowSharpness={5}
            depthTest={true}
          />
        </T.Mesh>
      </AutoColliders>

      <HTML
        transform
        position={[55.69, 3.8, -40.19]}
        occlude={true}
        rotation={[0, Math.PI / 1, 0]}
      >
        <div class="text-center">
          <p class="text-white text-[8px] w-full">Press E</p>
        </div>
      </HTML>
    </T.Group>

    <!-- Sensor -->

    <!-- Trash -->
    <T.Group position={[52.74, 0.47, -46.29]} rotation={[Math.PI / 2, 0, 0]}>
      <Collider
        args={[1.25, 0.5, 0.5]}
        shape="cuboid"
        oncollisionenter={handleJump}
      >
        <T.Mesh
          geometry={gltf.nodes.Trash_1.geometry}
          material={gltf.materials.FrontColor}
        />
        <T.Mesh
          geometry={gltf.nodes.Trash_2.geometry}
          material={gltf.materials["Material.009"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Trash_3.geometry}
          material={gltf.materials["Material.010"]}
        />
      </Collider>
    </T.Group>
    <!-- Trash -->

    <!-- Ground -->
    <AutoColliders shape="cuboid" oncollisionenter={handleJump}>
      <T.Mesh
        geometry={gltf.nodes.Island.geometry}
        material={gltf.materials["Material.001"]}
        position={[52.86, -0.51, -40.67]}
        rotation={[0, -0.07, 0]}
        scale={5}
      />
    </AutoColliders>
    <!-- Ground -->

    <!-- <T.Group position={[48.05, 2.97, -41.61]}>
      <T.Mesh
        geometry={gltf.nodes.SpaceShip001_1.geometry}
        material={gltf.materials['sui-sui-logo']}
      />
      <T.Mesh
        geometry={gltf.nodes.SpaceShip001_2.geometry}
        material={gltf.materials['Material.005']}
      />
      <T.Mesh
        geometry={gltf.nodes.SpaceShip001_3.geometry}
        material={gltf.materials['Material.004']}
      />
    </T.Group> -->

    <!-- PalmS -->
    <T.Group
      position={[40.52, 3.08, -39.99]}
      rotation={[-3.1, 0.31, -2.63]}
      scale={[0.16, 0.31, 0.63]}
    >
      <T.Mesh
        geometry={gltf.nodes.PalmStation001.geometry}
        material={gltf.materials["Material.003"]}
      />
      <T.Mesh
        geometry={gltf.nodes.PalmStation001_1.geometry}
        material={gltf.materials["Material.001"]}
      />
    </T.Group>
    <!-- PalmS -->

    <!-- <T.Mesh
      geometry={gltf.nodes.Adds.geometry}
      material={gltf.materials["Material.008"]}
      position={[51.4, 1.51, -38.68]}
      rotation={[Math.PI / 2, 0, 0]}
    /> -->

    <!-- Text -->

    <T.Mesh
      geometry={gltf.nodes.Space_Station_Text.geometry}
      transparent={true}
      position={[55.75, 4.55, -37.77]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={7.66}
    >
      <FakeGlowMaterial
        glowColor={`hsl(${currentColor.h}, ${currentColor.s}%, ${currentColor.l}%)`}
        falloff={1}
        glowInternalRadius={1}
        glowSharpness={0.5}
        depthTest={true}
      />
    </T.Mesh>
    <!-- Text -->

    <!-- Rocks -->
    <T.Mesh
      geometry={gltf.nodes.rocks.geometry}
      material={gltf.materials["Material.017"]}
      position={[41.37, -0.53, -41.51]}
      rotation={[-3.04, -0.03, 3.1]}
      scale={-0.87}
    />
    <!-- Rocks -->
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
