<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\main.glb -T --draco /draco/
-->

<script lang="ts">
  import { T } from "@threlte/core";
  import {
    FakeGlowMaterial,
    Sky,
    Text3DGeometry,
    useDraco,
    useGltf,
    Outlines,
    Edges,
  } from "@threlte/extras";
  import Water from "./Components/world/Water.svelte";
  import Ground from "./Components/world/Ground.svelte";
  import Boat from "./Components/world/Boat.svelte";
  import SpaceShip from "./Components/world/SpaceShip.svelte";
  import Globe from "./Components/world/Globe.svelte";

  let {
    fallback = () => {},
    error = () => {},
    children = () => {},
    ref = $bindable(),
    ...props
  } = $props();

  const gltf = useGltf("/main-transformed.glb", { dracoLoader: useDraco() });

  let currentColor = $state({ h: 180, s: 100, l: 50 }); // Cyan inicial en HSL
  let colorInterval = $state<any>();

  $effect(() => {
    // window.addEventListener("keydown", handleKeyDown);

    colorInterval = setInterval(() => {
      currentColor.h = (currentColor.h + 60) % 360; // Cambia el tono cada 2 segundos
    }, 2000);
    return () => {
      // window.removeEventListener("keydown", handleKeyDown);
      clearInterval(colorInterval);
    };
  });
</script>

<Globe />
<SpaceShip />
<Boat />
<Ground />
<Water />
<Sky elevation={0.5} azimuth={130} />

<T.PerspectiveCamera
  makeDefault
  fov={45}
  position={[-80, 15, 14]}
  oncreate={(ref) => {
    ref.lookAt(0, 0, 0);
  }}
/>

<T.Mesh position={[-10, 10, 0]} rotation={[0, Math.PI / -2, 0]}>
  <Text3DGeometry
    size={10}
    height={1}
    font="Dead Island_Regular.json"
    text={"ISLAND \n CLUB"}
    depth={0.2}
  />
  <FakeGlowMaterial glowColor="red" />
</T.Mesh>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Island.geometry}
      material={gltf.materials["Material.001"]}
      position={[52.49, -0.51, -41.12]}
      rotation={[0, -0.07, 0]}
      scale={5}
    />
    <T.Group position={[56.45, 2.51, -41.68]} rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Station_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Station_2.geometry}
        material={gltf.materials["Material.006"]}
      />
    </T.Group>
    <T.Group position={[52.7, 0.66, -46.28]} rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Trash_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Trash_2.geometry}
        material={gltf.materials["Material.009"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Trash_3.geometry}
        material={gltf.materials["Material.010"]}
      />
    </T.Group>
    <T.Group
      position={[5.54, 0.66, -16.38]}
      rotation={[Math.PI / 2, 0, Math.PI / 2]}
    >
      <T.Mesh
        geometry={gltf.nodes.Trash_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Trash_2.geometry}
        material={gltf.materials["Material.009"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Trash_3.geometry}
        material={gltf.materials["Material.010"]}
      />
    </T.Group>
    <T.Group
      position={[51.36, 1.5, -38.68]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={7}
    >
      <T.Mesh
        geometry={gltf.nodes.Sui001_1.geometry}
        material={gltf.materials["SVGMat.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Sui001_2.geometry}
        material={gltf.materials["Material.012"]}
      />
    </T.Group>
    <T.Group position={[48, 5.01, -45.8]} scale={[2, 5, 1]}>
      <T.Mesh
        geometry={gltf.nodes.Base_1.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Base_2.geometry}
        material={gltf.materials["Material.022"]}
      />
    </T.Group>
    <!-- <T.Group position={[47.98, 5.99, -41.01]} scale={[1, 5, 1]}>
      <T.Mesh
        geometry={gltf.nodes.SpaceShip005.geometry}
        material={gltf.materials["Material.020"]}
      />
      <T.Mesh
        geometry={gltf.nodes.SpaceShip005_1.geometry}
        material={gltf.materials["Material.021"]}
      />
      <T.Mesh
        geometry={gltf.nodes.SpaceShip005_2.geometry}
        material={gltf.materials["Material.021"]}
      />
    </T.Group> -->
    <T.Mesh
      geometry={gltf.nodes.rocks.geometry}
      material={gltf.materials["Material.017"]}
      position={[51.34, -0.46, -36.47]}
      rotation={[-3.04, -0.03, 3.1]}
      scale={-0.87}
    />
    <T.Group
      position={[51.35, 3.32, -35.93]}
      rotation={[-3.1, 0.31, -2.63]}
      scale={[0.16, 0.31, 0.63]}
    >
      <T.Mesh
        geometry={gltf.nodes.PalmStation001.geometry}
        material={gltf.materials["Material.003"]}
      />
      <T.Mesh
        geometry={gltf.nodes.PalmStation001_1.geometry}
        material={gltf.materials["Material.001"]}
      />
    </T.Group>

    <T.Mesh
      geometry={gltf.nodes.Space_Station_Text.geometry}
      material={gltf.materials.Material}
      position={[55.78, 4.49, -37.78]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={[7.66, 7.66, 7.83]}
    >
      <FakeGlowMaterial
        glowColor={`hsl(${currentColor.h}, ${currentColor.s}%, ${currentColor.l}%`}
        falloff={1}
        glowInternalRadius={1}
        glowSharpness={0.5}
        depthTest={true}
      />
    </T.Mesh>

    <T.Group position={[29.68, 2.4, -22.64]} rotation={[Math.PI / 2, 0, -0.56]}>
      <T.Mesh
        geometry={gltf.nodes.Pedestrian_bridge1_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Pedestrian_bridge1_2.geometry}
        material={gltf.materials["Material.006"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Circle007.geometry}
      material={gltf.materials["Material.058"]}
      position={[-54.64, 0.18, -2.06]}
      scale={11.66}
    />
    <T.Mesh
      geometry={gltf.nodes.Circle001.geometry}
      material={gltf.materials["Material.058"]}
      position={[-48.52, 0.18, 38.6]}
      rotation={[0, 1.18, 0]}
      scale={11.66}
    />
    <T.Mesh
      geometry={gltf.nodes.Puente.geometry}
      material={gltf.materials["Material.030"]}
      position={[-37.81, -0.07, -0.29]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[0.2, 0.5, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Puente001.geometry}
      material={gltf.materials["Material.030"]}
      position={[-32.6, -0.07, 26.76]}
      rotation={[0, -1, 0]}
      scale={[0.2, 0.5, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo002.geometry}
      material={gltf.materials["Material.035"]}
      position={[-38.04, 0.81, 0.53]}
      scale={[0.2, 2, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo004.geometry}
      material={gltf.materials["Material.035"]}
      position={[-32.36, 0.81, 27.58]}
      rotation={[0, 0.57, 0]}
      scale={[0.2, 2, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Rock1.geometry}
      material={gltf.materials["Material.034"]}
      position={[-57.3, -0.18, 6.88]}
      rotation={[0, -1.29, 0]}
      scale={1.2}
    />
    <T.Mesh
      geometry={gltf.nodes.Rock1001.geometry}
      material={gltf.materials["Material.034"]}
      position={[-41.29, -0.18, 44.5]}
      rotation={[0, -0.11, 0]}
      scale={1.2}
    />
    <T.Mesh
      geometry={gltf.nodes.Rock2001.geometry}
      material={gltf.materials["Material.034"]}
      position={[-54.87, -0.18, 32.61]}
      rotation={[0, 1.34, 0]}
      scale={1.2}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo003.geometry}
      material={gltf.materials["Material.035"]}
      position={[-43.28, 1, -1.44]}
      scale={[0.2, 2, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo005.geometry}
      material={gltf.materials["Material.035"]}
      position={[-40.34, 1, 30.34]}
      rotation={[0, 0.62, 0]}
      scale={[0.2, 2, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo.geometry}
      material={gltf.materials["Material.035"]}
      position={[-28.64, 3.54, -0.04]}
      rotation={[-Math.PI, 1.52, -Math.PI]}
      scale={[1, 4, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo001.geometry}
      material={gltf.materials["Material.035"]}
      position={[-30.47, 2.58, -0.63]}
      rotation={[Math.PI, -1.49, Math.PI]}
      scale={[0.83, 3.33, 0.83]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo006.geometry}
      material={gltf.materials["Material.035"]}
      position={[-24.73, 3.54, 22.05]}
      rotation={[-Math.PI, 0.95, -Math.PI]}
      scale={[1, 4, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo007.geometry}
      material={gltf.materials["Material.035"]}
      position={[-26.59, 2.58, 22.53]}
      rotation={[0, -1.09, 0]}
      scale={[0.83, 3.33, 0.83]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube025.geometry}
      material={gltf.materials["Material.057"]}
      position={[-27.96, 4.05, -0.68]}
      rotation={[0, 1.56, 0]}
      scale={[1.5, 0.4, 0.1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube012.geometry}
      material={gltf.materials["Material.057"]}
      position={[-24.49, 4.05, 21.15]}
      rotation={[-Math.PI, 1.02, -Math.PI]}
      scale={[1.5, 0.4, 0.1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve.geometry}
      material={gltf.materials["SVGMat.002"]}
      position={[-27.8, 4.03, -0.68]}
      rotation={[Math.PI / 2, 0, -1.56]}
      scale={2.74}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve004.geometry}
      material={gltf.materials["Material.049"]}
      position={[-56.89, 0.17, 8]}
      rotation={[0.45, -0.47, 2.95]}
      scale={12.75}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve002.geometry}
      material={gltf.materials["Material.049"]}
      position={[-40.11, 0.17, 44.55]}
      rotation={[0.49, 0.61, 2.44]}
      scale={12.75}
    />
    <T.Group
      position={[-54.33, 1.45, -2]}
      rotation={[Math.PI / 2, 0, -2.63]}
      scale={4}
    >
      <T.PointLight
        color="yellow"
        distance={5}
        intensity={10}
        position={[0, 0.5, -0.5]}
      />

      <T.PointLight
        color="red"
        distance={5}
        intensity={10}
        position={[0, 0.5, -0.5]}
      />

      <T.Mesh
        geometry={gltf.nodes.Cofre_1.geometry}
        material={gltf.materials["SVGMat.018"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cofre_2.geometry}
        material={gltf.materials["FrontColor.003"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cofre_3.geometry}
        material={gltf.materials["Material.056"]}
      />
    </T.Group>
    <T.Group
      position={[-48.35, 1.45, 38.34]}
      rotation={[Math.PI / 2, 0, 2.47]}
      scale={4}
    >
      <T.PointLight
        color={"yellow"}
        intensity={0.5}
        position={[0, 4, 0]}
        rotation={[0, 0, 0]}
      />

      <T.Mesh
        geometry={gltf.nodes.Cofre_1.geometry}
        material={gltf.materials["SVGMat.018"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cofre_2.geometry}
        material={gltf.materials["FrontColor.003"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cofre_3.geometry}
        material={gltf.materials["Material.056"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cylinder032.geometry}
      material={gltf.materials["Material.046"]}
      position={[-59.01, 4.39, -3.49]}
      rotation={[0, 0.55, 0]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder033.geometry}
      material={gltf.materials["Material.046"]}
      position={[-57.92, 2.99, -0.8]}
      rotation={[-2.88, 1.52, -3.03]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder034.geometry}
      material={gltf.materials["Material.046"]}
      position={[-56.38, 2.99, -4.54]}
      rotation={[-3.12, -0.83, -2.75]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder003.geometry}
      material={gltf.materials["Material.046"]}
      position={[-51.53, 4.39, 42.09]}
      rotation={[-Math.PI, 1.42, -Math.PI]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder005.geometry}
      material={gltf.materials["Material.046"]}
      position={[-48.62, 2.99, 42.12]}
      rotation={[-3.13, 0.34, -2.77]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder007.geometry}
      material={gltf.materials["Material.046"]}
      position={[-51.48, 2.99, 39.26]}
      rotation={[-0.03, -1.14, 0.35]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder013.geometry}
      material={gltf.materials["Material.046"]}
      position={[12.56, 8.12, -81.77]}
      rotation={[0, -1.01, 0.15]}
      scale={2.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder014.geometry}
      material={gltf.materials["Material.046"]}
      position={[13.99, 8.92, -80.15]}
      rotation={[-Math.PI, 1.17, -2.99]}
      scale={2.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder015.geometry}
      material={gltf.materials["Material.046"]}
      position={[12.16, 8.12, -79.59]}
      rotation={[0, 0.74, 0.15]}
      scale={2.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder017.geometry}
      material={gltf.materials["Material.046"]}
      position={[34, 8.2, -64.08]}
      rotation={[0.41, -1.01, 0.15]}
      scale={2.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder018.geometry}
      material={gltf.materials["Material.046"]}
      position={[35.43, 7.56, -62.58]}
      rotation={[-2.74, 1.17, -2.99]}
      scale={2.24}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder019.geometry}
      material={gltf.materials["Material.046"]}
      position={[33.6, 7.34, -62.07]}
      rotation={[0.41, 0.74, 0.15]}
      scale={2.24}
    />
    <T.Mesh
      geometry={gltf.nodes.RockaGrande.geometry}
      material={gltf.materials["Material.052"]}
      position={[-62.85, 4.07, -5.62]}
      rotation={[-Math.PI, 1.54, -Math.PI]}
      scale={[1.32, 3.96, 1.32]}
    />
    <T.Mesh
      geometry={gltf.nodes.RockaMediana.geometry}
      material={gltf.materials["Material.052"]}
      position={[-62.21, 1.96, -0.61]}
      rotation={[-2.61, 1.54, Math.PI]}
      scale={[0.88, 2.64, 0.88]}
    />
    <T.Mesh
      geometry={gltf.nodes.RockaMediana001.geometry}
      material={gltf.materials["Material.052"]}
      position={[-59.69, 1.9, -8.52]}
      rotation={[-2.81, 1.53, 2.27]}
      scale={[0.88, 2.64, 0.88]}
    />
    <T.Mesh
      geometry={gltf.nodes.RockaGrande002.geometry}
      material={gltf.materials["Material.052"]}
      position={[-54.97, 4.07, 44.81]}
      rotation={[-Math.PI, 0.37, -Math.PI]}
      scale={[1.32, 3.96, 1.32]}
    />
    <T.Mesh
      geometry={gltf.nodes.RockaMediana004.geometry}
      material={gltf.materials["Material.052"]}
      position={[-50.09, 1.96, 46.15]}
      rotation={[-3.13, 0.37, -2.61]}
      scale={[0.88, 2.64, 0.88]}
    />
    <T.Mesh
      geometry={gltf.nodes.RockaMediana005.geometry}
      material={gltf.materials["Material.052"]}
      position={[-56.43, 1.9, 40.77]}
      rotation={[-3.13, 0.35, 2.6]}
      scale={[0.88, 2.64, 0.88]}
    />
    <T.Group position={[-58.12, 0.27, 5.56]} scale={[1.4, 2, 1.4]}>
      <T.Mesh
        geometry={gltf.nodes.Barril1_1.geometry}
        material={gltf.materials["Material.054"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Barril1_2.geometry}
        material={gltf.materials["Material.055"]}
      />
    </T.Group>
    <T.Group
      position={[-50.57, 0.18, 2.58]}
      rotation={[-1.52, 0, 0]}
      scale={[1.4, 2, 1.4]}
    >
      <T.Mesh
        geometry={gltf.nodes.Barril1_1.geometry}
        material={gltf.materials["Material.054"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Barril1_2.geometry}
        material={gltf.materials["Material.055"]}
      />
    </T.Group>
    <T.Group
      position={[-42.82, 0.27, 44.75]}
      rotation={[0, 1.18, 0]}
      scale={[1.4, 2, 1.4]}
    >
      <T.Mesh
        geometry={gltf.nodes.Barril1_1.geometry}
        material={gltf.materials["Material.054"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Barril1_2.geometry}
        material={gltf.materials["Material.055"]}
      />
    </T.Group>
    <T.Group
      position={[-42.68, 0.18, 36.64]}
      rotation={[-1.55, 0.05, 1.17]}
      scale={[1.4, 2, 1.4]}
    >
      <T.Mesh
        geometry={gltf.nodes.Barril1_1.geometry}
        material={gltf.materials["Material.054"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Barril1_2.geometry}
        material={gltf.materials["Material.055"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Plane024.geometry}
      material={gltf.materials["Material.047"]}
      position={[-57.48, 5.49, 3.06]}
      rotation={[-2.76, -0.84, -3.13]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane004.geometry}
      material={gltf.materials["Material.047"]}
      position={[-44.89, 5.49, 43.2]}
      rotation={[-0.5, -1.03, -0.73]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane025.geometry}
      material={gltf.materials["Material.047"]}
      position={[-50.82, -0.27, 6.34]}
      rotation={[3.09, -0.5, 3]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane026.geometry}
      material={gltf.materials["Material.047"]}
      position={[-59.98, 8.14, -2.28]}
      rotation={[-Math.PI, 0.24, -Math.PI]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane028.geometry}
      material={gltf.materials["Material.047"]}
      position={[-54.91, 5.95, -6.89]}
      rotation={[-0.25, 0.08, -0.26]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane009.geometry}
      material={gltf.materials["Material.047"]}
      position={[-50.77, 8.14, 43.44]}
      rotation={[Math.PI, -0.94, Math.PI]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane011.geometry}
      material={gltf.materials["Material.047"]}
      position={[-53.08, 5.95, 36.99]}
      rotation={[-0.7, 1.17, 0.38]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane017.geometry}
      material={gltf.materials["Material.047"]}
      position={[11.72, 10.02, -82.54]}
      rotation={[-0.47, 1.33, 0.35]}
      scale={[0.26, 0.33, 0.78]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane018.geometry}
      material={gltf.materials["Material.047"]}
      position={[14.68, 10.92, -79.25]}
      rotation={[-2.86, -1.18, -2.99]}
      scale={[0.26, 0.33, 0.78]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane019.geometry}
      material={gltf.materials["Material.047"]}
      position={[11.55, 10.02, -78.63]}
      rotation={[-3.04, 0.04, 3.03]}
      scale={[0.26, 0.33, 0.78]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane020.geometry}
      material={gltf.materials["Material.047"]}
      position={[33.16, 10.26, -64.03]}
      rotation={[-0.06, 1.33, 0.35]}
      scale={[0.26, 0.33, 0.78]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane021.geometry}
      material={gltf.materials["Material.047"]}
      position={[36.13, 8.96, -61.01]}
      rotation={[-2.46, -1.18, -2.99]}
      scale={[0.26, 0.33, 0.78]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane022.geometry}
      material={gltf.materials["Material.047"]}
      position={[32.99, 8.72, -60.44]}
      rotation={[-2.63, 0.04, 3.03]}
      scale={[0.26, 0.33, 0.78]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane027.geometry}
      material={gltf.materials["Material.047"]}
      position={[-57.28, 5.95, 1.9]}
      rotation={[-2.76, -0.84, -3.13]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane010.geometry}
      material={gltf.materials["Material.047"]}
      position={[-45.88, 5.95, 42.56]}
      rotation={[-0.5, -1.03, -0.73]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane029.geometry}
      material={gltf.materials["Material.047"]}
      position={[-49.89, -0.23, 5.88]}
      rotation={[0.7, -1.5, 0.58]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane030.geometry}
      material={gltf.materials["Material.047"]}
      position={[-49.44, -0.22, 4.85]}
      rotation={[0.07, -0.81, -0.07]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane031.geometry}
      material={gltf.materials["Material.047"]}
      position={[-46.77, -0.27, -5.96]}
      rotation={[2.81, -1.43, 2.69]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane032.geometry}
      material={gltf.materials["Material.047"]}
      position={[-46.58, -0.23, -6.97]}
      rotation={[0.06, -0.58, -0.09]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane033.geometry}
      material={gltf.materials["Material.047"]}
      position={[-47.15, -0.22, -7.95]}
      rotation={[0.05, 0.13, -0.12]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane008.geometry}
      material={gltf.materials["Material.047"]}
      position={[-39.3, -0.27, 38.31]}
      rotation={[0.43, -1.46, 0.31]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane012.geometry}
      material={gltf.materials["Material.047"]}
      position={[-39.36, -0.23, 37.28]}
      rotation={[0.05, -0.34, -0.1]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane013.geometry}
      material={gltf.materials["Material.047"]}
      position={[-40.15, -0.22, 36.47]}
      rotation={[0.05, 0.37, -0.14]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane014.geometry}
      material={gltf.materials["Material.047"]}
      position={[-49.09, -0.27, 29.84]}
      rotation={[0.05, -0.53, -0.09]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane015.geometry}
      material={gltf.materials["Material.047"]}
      position={[-49.95, -0.23, 29.28]}
      rotation={[0.06, 0.6, -0.15]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane016.geometry}
      material={gltf.materials["Material.047"]}
      position={[-51.07, -0.22, 29.43]}
      rotation={[0.18, 1.3, -0.29]}
      scale={[0.47, 0.6, 1.42]}
    />

    <T.Group position={[-63.88, 11.08, -5.97]} rotation={[0, 1.16, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Calabera.geometry}
        material={gltf.materials["Material.053"]}
        scale={15.36}
      />
      <T.PointLight
        color="red"
        distance={4}
        intensity={10}
        power={1000}
        position={[0, 0, 0]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Calabera001.geometry}
      material={gltf.materials["Material.053"]}
      position={[-55.68, 11.08, 45.62]}
      rotation={[-Math.PI, 0.81, -Math.PI]}
      scale={15.36}
    />

    <!-- <T.Group position={[-4.6, 3, 29.45]} scale={1.5}>
      <T.Mesh
        geometry={gltf.nodes.Plane045.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_1.geometry}
        material={gltf.materials["Material.063"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_2.geometry}
        material={gltf.materials["border oro.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_3.geometry}
        material={gltf.materials["Material.064"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_4.geometry}
        material={gltf.materials["Material.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_5.geometry}
        material={gltf.materials["Material.066"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_6.geometry}
        material={gltf.materials["Material.067"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_7.geometry}
        material={gltf.materials["Material.068"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_8.geometry}
        material={gltf.materials["Material.069"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_9.geometry}
        material={gltf.materials["Material.063"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_10.geometry}
        material={gltf.materials["Material.070"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_11.geometry}
        material={gltf.materials["Material.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_12.geometry}
        material={gltf.materials["Material.075"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_13.geometry}
        material={gltf.materials["Material.076"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_14.geometry}
        material={gltf.materials["Material.063"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane045_15.geometry}
        material={gltf.materials["Material.063"]}
      />
    </T.Group> -->

    <T.Mesh
      geometry={gltf.nodes.ADD.geometry}
      material={gltf.nodes.ADD.material}
      position={[0, 0.3, 0]}
      scale={0.29}
    />
    <T.Mesh
      geometry={gltf.nodes.Sui.geometry}
      material={gltf.materials.SVGMat}
      position={[-0.03, 1.92, 0]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={9.21}
    />

    <T.Mesh
      geometry={gltf.nodes.Sui002.geometry}
      material={gltf.materials.SVGMat}
      position={[20.9, 1.92, 0]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={9.21}
    >
      <FakeGlowMaterial
        glowColor={`hsl(${currentColor.h}, ${currentColor.s}%, ${currentColor.l}%)`}
        falloff={1}
        glowInternalRadius={1}
        glowSharpness={0.5}
        depthTest={true}
      />
    </T.Mesh>

    <T.Mesh
      geometry={gltf.nodes.Ground.geometry}
      material={gltf.materials["Material.001"]}
      position={[-1.74, -0.51, -0.83]}
      scale={[10, 5, 10]}
    />
    <T.Mesh
      geometry={gltf.nodes.Home1.geometry}
      material={gltf.nodes.Home1.material}
      position={[-14.16, 2.34, -9.84]}
      rotation={[0, 0.84, 0]}
      scale={[2, 1, 2]}
    />
    <T.Group position={[-10.04, 3.05, -11.55]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder001_1.geometry}
        material={gltf.materials["Material.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder001_2.geometry}
        material={gltf.materials["Material.003"]}
      />
    </T.Group>
    <T.Group
      position={[14.65, 3.05, -6.13]}
      rotation={[Math.PI, -1.48, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder004_1.geometry}
        material={gltf.materials["Material.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder004_2.geometry}
        material={gltf.materials["Material.003"]}
      />
    </T.Group>
    <T.Group
      position={[-10.8, 1.54, -11.68]}
      rotation={[0, 0, 0.46]}
      scale={0.58}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder006_1.geometry}
        material={gltf.materials["Material.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder006_2.geometry}
        material={gltf.materials["Material.003"]}
      />
    </T.Group>
    <T.Group
      position={[-9.14, 1.62, -12.13]}
      rotation={[3.01, 1.01, -2.49]}
      scale={[0.14, 0.27, 0.54]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane033_1.geometry}
        material={gltf.materials["Material.003"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane033_2.geometry}
        material={gltf.materials["Material.001"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube003.geometry}
      material={gltf.materials["Material.016"]}
      position={[17.12, -0.06, 16.79]}
      rotation={[0, -0.18, 0]}
      scale={0.6}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube005.geometry}
      material={gltf.materials["Material.016"]}
      position={[21.79, -0.04, 17.17]}
      rotation={[-0.55, -0.97, 0.7]}
      scale={0.19}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube006.geometry}
      material={gltf.materials["Material.016"]}
      position={[20.17, 0.25, 15.09]}
      rotation={[0, -1.44, 0]}
      scale={0.22}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube007.geometry}
      material={gltf.materials["Material.016"]}
      position={[19.73, 0.09, 15.15]}
      rotation={[-2.65, -0.9, -1.58]}
      scale={0.19}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube008.geometry}
      material={gltf.materials["Material.016"]}
      position={[21.6, -0.03, 17.59]}
      rotation={[-2.83, -0.28, -1.89]}
      scale={0.13}
    />
    <T.Mesh
      geometry={gltf.nodes.PuenteGrande.geometry}
      material={gltf.materials["Material.030"]}
      position={[0, -0.09, 33.13]}
      scale={[0.4, 1.01, 0.4]}
    />
    <T.Group
      position={[-16.72, 8.77, -22.48]}
      rotation={[0, 0, 0.09]}
      scale={[0.2, 2.5, 0.2]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube040.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube040_1.geometry}
        material={gltf.materials["Material.037"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube040_2.geometry}
        material={gltf.materials["Material.022"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube021.geometry}
      material={gltf.materials["Material.039"]}
      position={[-17.97, 6.96, -22.48]}
      scale={0.2}
    />
    <T.Group
      position={[-17.47, 2.49, -21.91]}
      rotation={[0, -0.29, 0]}
      scale={3.16}
    >
      <T.Mesh
        geometry={gltf.nodes.bigStone_1.geometry}
        material={gltf.materials["Material.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bigStone_2.geometry}
        material={gltf.materials["Material.008"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bigStone_3.geometry}
        material={gltf.materials["Material.014"]}
      />
    </T.Group>
    <T.Group
      position={[-23.79, 10.06, -21.13]}
      rotation={[-3.09, 0.72, -2.65]}
      scale={[0.16, 0.31, 0.63]}
    >
      <T.Mesh
        geometry={gltf.nodes.PalmStation004_1.geometry}
        material={gltf.materials["Material.003"]}
      />
      <T.Mesh
        geometry={gltf.nodes.PalmStation004_2.geometry}
        material={gltf.materials["Material.001"]}
      />
    </T.Group>
    <T.Group position={[19.62, 2.15, 17.21]} rotation={[Math.PI / 2, 0, 2.53]}>
      <T.Mesh
        geometry={gltf.nodes.Untitled001_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Untitled001_2.geometry}
        material={gltf.materials["Material.006"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.MusicSpot.geometry}
      material={gltf.materials["Material.023"]}
      position={[19.48, 0.36, 0]}
      rotation={[Math.PI / 2, 0, Math.PI]}
    />
    <T.Group position={[19.48, 1.55, 0]} rotation={[Math.PI / 2, 0, Math.PI]}>
      <T.Mesh
        geometry={gltf.nodes.MusicSpot001_1.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.MusicSpot001_2.geometry}
        material={gltf.materials["Material.006"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.materials["Material.017"]}
      position={[21.68, -0.26, 13.89]}
      rotation={[Math.PI, -1.56, Math.PI]}
      scale={0.6}
    />
    <T.Group
      position={[22.03, 1.97, 13.72]}
      rotation={[0.58, 0.35, -0.21]}
      scale={[0.16, 0.32, 0.64]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane006_1.geometry}
        material={gltf.materials["Material.003"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane006_2.geometry}
        material={gltf.materials["Material.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane006_3.geometry}
        material={gltf.materials["Material.017"]}
      />
    </T.Group>
    <T.Group
      position={[15.98, 5.94, 21.86]}
      rotation={[0, 0, 0.09]}
      scale={[0.2, 2.5, 0.2]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube006_1.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_2.geometry}
        material={gltf.materials["Material.037"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_3.geometry}
        material={gltf.materials["Material.022"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_4.geometry}
        material={gltf.materials["Material.039"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_5.geometry}
        material={gltf.materials["Material.030"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_6.geometry}
        material={gltf.materials["Material.030"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube006_7.geometry}
        material={gltf.materials["Material.030"]}
      />
    </T.Group>
    <T.Group
      position={[-12.48, 2.17, 20.37]}
      rotation={[-0.82, 0.18, 0.36]}
      scale={[0.16, 0.32, 0.64]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane040.geometry}
        material={gltf.materials["Material.003"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane040_1.geometry}
        material={gltf.materials["Material.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane040_2.geometry}
        material={gltf.materials["Material.017"]}
      />
    </T.Group>
    <T.Group position={[0, 0.94, 33.04]} scale={[0.4, 1.01, 0.4]}>
      <T.Mesh
        geometry={gltf.nodes.PuenteGrande001_1.geometry}
        material={gltf.materials["Material.018"]}
      />
      <T.Mesh
        geometry={gltf.nodes.PuenteGrande001_2.geometry}
        material={gltf.materials["Material.018"]}
      />
      <T.Mesh
        geometry={gltf.nodes.PuenteGrande001_3.geometry}
        material={gltf.materials["Material.018"]}
      />
    </T.Group>
    <T.Group position={[0, 2.51, -15.4]} rotation={[Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes.Station001_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Station001_2.geometry}
        material={gltf.materials["Material.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Station001_3.geometry}
        material={gltf.materials["Material.025"]}
      />
    </T.Group>
    <T.Group
      position={[-24.48, 4.52, 9.78]}
      rotation={[0, -1.01, 0.15]}
      scale={2.24}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder009_1.geometry}
        material={gltf.materials["Material.046"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder009_2.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder009_3.geometry}
        material={gltf.materials["Material.034"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder009_4.geometry}
        material={gltf.materials["Material.050"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder009_5.geometry}
        material={gltf.materials["Material.051"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder009_6.geometry}
        material={gltf.materials["Material.047"]}
      />
    </T.Group>
    <T.Group
      position={[12.12, 4.19, -21]}
      rotation={[Math.PI, -0.59, Math.PI]}
      scale={[1, 3, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder021_1.geometry}
        material={gltf.materials["Material.050"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder021_2.geometry}
        material={gltf.materials["Material.051"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder021_3.geometry}
        material={gltf.materials["Material.017"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder021_4.geometry}
        material={gltf.materials["Material.034"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder021_5.geometry}
        material={gltf.materials["Material.046"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder021_6.geometry}
        material={gltf.materials["Material.047"]}
      />
    </T.Group>
    <T.Group position={[18.34, 2.4, -2.9]} rotation={[Math.PI / 2, 0, Math.PI]}>
      <T.Mesh
        geometry={gltf.nodes.MusicSpot002_1.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.MusicSpot002_2.geometry}
        material={gltf.materials["Material.006"]}
      />
    </T.Group>
    <T.Group position={[18.34, 2.4, 3.1]} rotation={[Math.PI / 2, 0, Math.PI]}>
      <T.Mesh
        geometry={gltf.nodes.MusicSpot003_1.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.MusicSpot003_2.geometry}
        material={gltf.materials["Material.006"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.store_text.geometry}
      material={gltf.nodes.store_text.material}
      position={[-0.91, 4.44, -11.51]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={[5.44, 6.07, 5.49]}
    >
      <FakeGlowMaterial
        glowColor={`hsl(${currentColor.h}, ${currentColor.s}%, ${currentColor.l}%)`}
        falloff={1}
        glowInternalRadius={1}
        glowSharpness={0.5}
        depthTest={true}
      />
    </T.Mesh>

    <!-- <T.Group position={[23.26, 3, -76.9]} rotation={[0, -1.23, 0]} scale={1.5}>
      <T.Mesh
        geometry={gltf.nodes.bote002_1.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_2.geometry}
        material={gltf.materials["Material.063"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_3.geometry}
        material={gltf.materials["border oro.001"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_4.geometry}
        material={gltf.materials["Material.064"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_5.geometry}
        material={gltf.materials["Material.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_6.geometry}
        material={gltf.materials["Material.066"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_7.geometry}
        material={gltf.materials["Material.067"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_8.geometry}
        material={gltf.materials["Material.068"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_9.geometry}
        material={gltf.materials["Material.069"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_10.geometry}
        material={gltf.materials["Material.063"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_11.geometry}
        material={gltf.materials["Material.070"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_12.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_13.geometry}
        material={gltf.materials["Material.071"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_14.geometry}
        material={gltf.materials["Material.072"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_15.geometry}
        material={gltf.materials["Material.063"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_16.geometry}
        material={gltf.materials["Material.006"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_17.geometry}
        material={gltf.materials["Material.075"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_18.geometry}
        material={gltf.materials["Material.076"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_19.geometry}
        material={gltf.materials["Material.063"]}
      />
      <T.Mesh
        geometry={gltf.nodes.bote002_20.geometry}
        material={gltf.materials["Material.063"]}
      />
    </T.Group> -->

    <T.Mesh
      geometry={gltf.nodes.Curve007.geometry}
      material={gltf.materials["Material.020"]}
      position={[-24.41, 4.05, 21.03]}
      rotation={[Math.PI / 2, 0, -2.12]}
      scale={[1.5, 0.68, 1.5]}
    />
    <T.Group
      position={[-45.09, -0.61, 30.35]}
      rotation={[0, 0, 0.61]}
      scale={0.31}
    >
      <T.Mesh
        geometry={gltf.nodes.Escalera1.geometry}
        material={gltf.materials["Material.035"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Escalera1_1.geometry}
        material={gltf.materials["Material.035"]}
      />
    </T.Group>
    <T.Group position={[-38.14, 5.94, -66.63]} scale={0.64}>
      <T.Mesh
        geometry={gltf.nodes.Circle003.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle003_1.geometry}
        material={gltf.materials.azul}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle003_2.geometry}
        material={gltf.materials["Material.081"]}
      />
    </T.Group>
    <T.Group position={[49.59, 5.94, -0.14]} scale={0.64}>
      <T.Mesh
        geometry={gltf.nodes.Circle003.geometry}
        material={gltf.materials["Material.023"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle003_1.geometry}
        material={gltf.materials.azul}
      />
      <T.Mesh
        geometry={gltf.nodes.Circle003_2.geometry}
        material={gltf.materials["Material.081"]}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Plane041.geometry}
      material={gltf.materials["Material.079"]}
      position={[-37.91, -2.37, -66.13]}
      scale={0.64}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane.geometry}
      material={gltf.materials["Material.079"]}
      position={[49.82, -2.37, 0.36]}
      scale={0.64}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.materials["Material.034"]}
      position={[26.16, 6.56, -75.88]}
      rotation={[-0.14, -0.72, -0.09]}
      scale={1.53}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials["Material.034"]}
      position={[13.02, 6.95, -80.41]}
      scale={0.58}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube014.geometry}
      material={gltf.materials["Material.034"]}
      position={[34.66, 6.63, -63.5]}
      rotation={[0.29, 0, 0]}
      scale={0.7}
    />
    <T.Group position={[13.01, 3.12, -80.06]} scale={[1, 3, 1]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder016_1.geometry}
        material={gltf.materials["Material.050"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder016_2.geometry}
        material={gltf.materials["Material.051"]}
      />
    </T.Group>
    <T.Group
      position={[34.45, 2.93, -64.48]}
      rotation={[0.41, 0, 0]}
      scale={[1, 3, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder016_1.geometry}
        material={gltf.materials["Material.050"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder016_2.geometry}
        material={gltf.materials["Material.051"]}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
