<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\parkour.glb -T --draco /draco/
-->

<script>
  import { T } from "@threlte/core";
  import { useGltf, useDraco, FakeGlowMaterial } from "@threlte/extras";
  import { AutoColliders, Collider } from "@threlte/rapier";
  import { handleJump } from "../../utils/utils";

  let {
    fallback = () => {},
    error = () => {},
    children = () => {},
    ref = $bindable(),
    ...props
  } = $props();

  const gltf = useGltf("/parkour-transformed.glb", { dracoLoader: useDraco() });
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[-42.82, 0.27, 44.75]}
      rotation={[0, 1.18, 0]}
      scale={[1.4, 2, 1.4]}
    >
      <Collider
        shape="cuboid"
        args={[0.45, 0.35, 0.45]}
        oncollisionenter={handleJump}
      >
        <T.Mesh
          geometry={gltf.nodes.Barril1001_1.geometry}
          material={gltf.materials["Material.054"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Barril1001_2.geometry}
          material={gltf.materials["Material.055"]}
        />
      </Collider>
    </T.Group>
    <T.Group
      position={[-42.68, 0.18, 36.64]}
      rotation={[-1.55, 0.05, 1.17]}
      scale={[1.4, 2, 1.4]}
    >
      <Collider
        shape="cuboid"
        args={[0.45, 0.35, 0.45]}
        oncollisionenter={handleJump}
      >
        <T.Mesh
          geometry={gltf.nodes.Barril1001_1.geometry}
          material={gltf.materials["Material.054"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Barril1001_2.geometry}
          material={gltf.materials["Material.055"]}
        />
      </Collider>
    </T.Group>
    <T.Group
      position={[-55.68, 11.08, 45.62]}
      rotation={[-Math.PI, 0.81, -Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Calabera001.geometry}
        material={gltf.materials["Material.053"]}
        scale={15.36}
      />

      <T.PointLight
        color="red"
        distance={4}
        intensity={10}
        power={1000}
        position={[0, 0, 0]}
      />
    </T.Group>

    <AutoColliders shape="convexHull" oncollisionenter={handleJump}>
      <T.Mesh
        geometry={gltf.nodes.Circle001.geometry}
        material={gltf.materials["Material.058"]}
        position={[-48.52, 0.18, 38.6]}
        rotation={[0, 1.18, 0]}
        scale={11.66}
      />
    </AutoColliders>
    <T.Group
      position={[-48.35, 1.45, 38.34]}
      rotation={[Math.PI / 2, 0, 2.47]}
      scale={4}
    >
      <Collider
        shape="cuboid"
        args={[0.14, 0.25, 0.19]}
        oncollisionenter={handleJump}
      >
        <T.Mesh
          geometry={gltf.nodes.Cofre001_1.geometry}
          material={gltf.materials["SVGMat.018"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cofre001_2.geometry}
          material={gltf.materials["FrontColor.003"]}
        />
        <T.Mesh
          geometry={gltf.nodes.Cofre001_3.geometry}
          material={gltf.materials["Material.056"]}
        />
      </Collider>
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube012.geometry}
      material={gltf.materials["Material.057"]}
      position={[-24.49, 4.05, 21.15]}
      rotation={[-Math.PI, 1.02, -Math.PI]}
      scale={[1.5, 0.4, 0.1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve002.geometry}
      material={gltf.materials["Material.049"]}
      position={[-40.11, 0.17, 44.55]}
      rotation={[0.49, 0.61, 2.44]}
      scale={12.75}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder003.geometry}
      material={gltf.materials["Material.046"]}
      position={[-51.53, 4.39, 42.09]}
      rotation={[-Math.PI, 1.42, -Math.PI]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder005.geometry}
      material={gltf.materials["Material.046"]}
      position={[-48.62, 2.99, 42.12]}
      rotation={[-3.13, 0.34, -2.77]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder007.geometry}
      material={gltf.materials["Material.046"]}
      position={[-51.48, 2.99, 39.26]}
      rotation={[-0.03, -1.14, 0.35]}
      scale={4.1}
    />
    <T.Group position={[-32.36, 0.81, 27.58]} rotation={[0, 0.57, 0]}>
      <Collider
        shape="cuboid"
        args={[0.2, 2, 0.2]}
        oncollisionenter={handleJump}
      >
        <T.Mesh
          geometry={gltf.nodes.Palo004.geometry}
          material={gltf.materials["Material.035"]}
          scale={[0.2, 2, 0.2]}
        />
      </Collider>
    </T.Group>

    <T.Group position={[-40.34, 1, 30.6]} rotation={[0, 0.62, 0]}>
      <Collider
        shape="cuboid"
        args={[0.2, 2, 0.2]}
        oncollisionenter={handleJump}
      >
        <T.Mesh
          geometry={gltf.nodes.Palo005.geometry}
          material={gltf.materials["Material.035"]}
          scale={[0.2, 2, 0.2]}
          position={[0, 0, -0.3]}
        />
      </Collider>
    </T.Group>

    <T.Mesh
      geometry={gltf.nodes.Palo006.geometry}
      material={gltf.materials["Material.035"]}
      position={[-24.73, 3.54, 22.05]}
      rotation={[-Math.PI, 0.95, -Math.PI]}
      scale={[1, 4, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Palo007.geometry}
      material={gltf.materials["Material.035"]}
      position={[-26.59, 2.58, 22.53]}
      rotation={[0, -1.09, 0]}
      scale={[0.83, 3.33, 0.83]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane004.geometry}
      material={gltf.materials["Material.047"]}
      position={[-44.89, 5.49, 43.2]}
      rotation={[-0.5, -1.03, -0.73]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane008.geometry}
      material={gltf.materials["Material.047"]}
      position={[-39.3, -0.27, 38.31]}
      rotation={[0.43, -1.46, 0.31]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane009.geometry}
      material={gltf.materials["Material.047"]}
      position={[-50.77, 8.14, 43.44]}
      rotation={[Math.PI, -0.94, Math.PI]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane011.geometry}
      material={gltf.materials["Material.047"]}
      position={[-53.08, 5.95, 36.99]}
      rotation={[-0.7, 1.17, 0.38]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane010.geometry}
      material={gltf.materials["Material.047"]}
      position={[-45.88, 5.95, 42.56]}
      rotation={[-0.5, -1.03, -0.73]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane012.geometry}
      material={gltf.materials["Material.047"]}
      position={[-39.36, -0.23, 37.28]}
      rotation={[0.05, -0.34, -0.1]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane013.geometry}
      material={gltf.materials["Material.047"]}
      position={[-40.15, -0.22, 36.47]}
      rotation={[0.05, 0.37, -0.14]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane014.geometry}
      material={gltf.materials["Material.047"]}
      position={[-49.09, -0.27, 29.84]}
      rotation={[0.05, -0.53, -0.09]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane015.geometry}
      material={gltf.materials["Material.047"]}
      position={[-49.95, -0.23, 29.28]}
      rotation={[0.06, 0.6, -0.15]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane016.geometry}
      material={gltf.materials["Material.047"]}
      position={[-51.07, -0.22, 29.43]}
      rotation={[0.18, 1.3, -0.29]}
      scale={[0.47, 0.6, 1.42]}
    />
    <AutoColliders shape="cuboid" oncollisionenter={handleJump}>
      <T.Mesh
        geometry={gltf.nodes.Puente001.geometry}
        material={gltf.materials["Material.030"]}
        position={[-32.6, -0.07, 26.76]}
        rotation={[0, -1, 0]}
        scale={[0.2, 0.5, 0.2]}
      />
    </AutoColliders>

    <AutoColliders shape="convexHull" oncollisionenter={handleJump}>
      <T.Mesh
        geometry={gltf.nodes.Rock1001.geometry}
        material={gltf.materials["Material.034"]}
        position={[-41.29, -0.18, 44.5]}
        rotation={[0, -0.11, 0]}
        scale={1.2}
      />
      <T.Mesh
        geometry={gltf.nodes.Rock2001.geometry}
        material={gltf.materials["Material.034"]}
        position={[-54.87, -0.18, 32.61]}
        rotation={[0, 1.34, 0]}
        scale={1.2}
      />
      <T.Mesh
        geometry={gltf.nodes.RockaGrande002.geometry}
        material={gltf.materials["Material.052"]}
        position={[-54.97, 4.07, 44.81]}
        rotation={[-Math.PI, 0.37, -Math.PI]}
        scale={[1.32, 3.96, 1.32]}
      />
      <T.Mesh
        geometry={gltf.nodes.RockaMediana004.geometry}
        material={gltf.materials["Material.052"]}
        position={[-50.09, 1.96, 46.15]}
        rotation={[-3.13, 0.37, -2.61]}
        scale={[0.88, 2.64, 0.88]}
      />
      <T.Mesh
        geometry={gltf.nodes.RockaMediana005.geometry}
        material={gltf.materials["Material.052"]}
        position={[-56.43, 1.9, 40.77]}
        rotation={[-3.13, 0.35, 2.6]}
        scale={[0.88, 2.64, 0.88]}
      />
    </AutoColliders>

    <T.Mesh
      geometry={gltf.nodes.Curve007.geometry}
      material={gltf.materials["Material.042"]}
      position={[-24.41, 4.05, 21.03]}
      rotation={[Math.PI / 2, 0, -2.12]}
      scale={[1.5, 0.68, 1.5]}
    >
      <FakeGlowMaterial
        glowColor={"darkred"}
        falloff={1}
        glowInternalRadius={5}
        glowSharpness={1}
        depthTest={true}
      />
    </T.Mesh>

    <T.Group
      position={[-45.09, -0.61, 30.35]}
      rotation={[0, 0, 0.61]}
      scale={0.31}
    >
      <T.Mesh
        geometry={gltf.nodes.Escalera1.geometry}
        material={gltf.materials["Material.035"]}
      />
      <T.Mesh
        geometry={gltf.nodes.Escalera1_1.geometry}
        material={gltf.materials["Material.035"]}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
