<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\referencies.glb -T --draco /draco/
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/referencies-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[3.2, 0.66, -12.19]}
      rotation={[Math.PI / 2, 0, Math.PI / 2]}
    >
      <T.Mesh
        geometry={gltf.nodes.Trash001_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Trash001_2.geometry}
        material={gltf.materials['Material.009']}
      />
      <T.Mesh
        geometry={gltf.nodes.Trash001_3.geometry}
        material={gltf.materials['Material.010']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Circle007.geometry}
      material={gltf.materials['Material.058']}
      position={[-54.64, 0.18, -2.06]}
      scale={11.66}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder035.geometry}
      material={gltf.materials['Material.052']}
      position={[-62.85, 4.07, -5.62]}
      rotation={[-Math.PI, 1.54, -Math.PI]}
      scale={[1.32, 3.96, 1.32]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder036.geometry}
      material={gltf.materials['Material.052']}
      position={[-62.21, 1.96, -0.61]}
      rotation={[-2.61, 1.54, Math.PI]}
      scale={[0.88, 2.64, 0.88]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder037.geometry}
      material={gltf.materials['Material.052']}
      position={[-59.69, 1.9, -8.52]}
      rotation={[-2.81, 1.53, 2.27]}
      scale={[0.88, 2.64, 0.88]}
    />
    <T.Group
      position={[-58.12, 0.27, 5.56]}
      scale={[1.4, 2, 1.4]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder042.geometry}
        material={gltf.materials['Material.054']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder042_1.geometry}
        material={gltf.materials['Material.055']}
      />
    </T.Group>
    <T.Group
      position={[-50.57, 0.18, 2.58]}
      rotation={[-1.52, 0, 0]}
      scale={[1.4, 2, 1.4]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder042.geometry}
        material={gltf.materials['Material.054']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder042_1.geometry}
        material={gltf.materials['Material.055']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube023.geometry}
      material={gltf.materials['Material.048']}
      position={[-28.64, 3.54, -0.04]}
      rotation={[-Math.PI, 1.52, -Math.PI]}
      scale={[1, 4, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube024.geometry}
      material={gltf.materials['Material.048']}
      position={[-30.47, 2.58, -0.63]}
      rotation={[Math.PI, -1.49, Math.PI]}
      scale={[0.83, 3.33, 0.83]}
    />
    <T.Mesh
      geometry={gltf.nodes.RetopoFlow.geometry}
      material={gltf.materials['Material.053']}
      position={[-63.88, 11.08, -5.97]}
      rotation={[0, 1.16, 0]}
      scale={15.36}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube015.geometry}
      material={gltf.materials['Material.034']}
      position={[-57.3, -0.18, 6.88]}
      rotation={[0, -1.29, 0]}
      scale={1.2}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube016.geometry}
      material={gltf.materials['Material.034']}
      position={[-51.55, -0.18, -10.23]}
      rotation={[0, 0.16, 0]}
      scale={1.2}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder032.geometry}
      material={gltf.materials['Material.046']}
      position={[-59.01, 4.39, -3.49]}
      rotation={[0, 0.55, 0]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder033.geometry}
      material={gltf.materials['Material.046']}
      position={[-57.92, 2.99, -0.8]}
      rotation={[-2.88, 1.52, -3.03]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Cylinder034.geometry}
      material={gltf.materials['Material.046']}
      position={[-56.38, 2.99, -4.54]}
      rotation={[-3.12, -0.83, -2.75]}
      scale={4.1}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane026.geometry}
      material={gltf.materials['Material.047']}
      position={[-59.98, 8.14, -2.28]}
      rotation={[-Math.PI, 0.24, -Math.PI]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane028.geometry}
      material={gltf.materials['Material.047']}
      position={[-54.91, 5.95, -6.89]}
      rotation={[-0.25, 0.08, -0.26]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane027.geometry}
      material={gltf.materials['Material.047']}
      position={[-57.28, 5.95, 1.9]}
      rotation={[-2.76, -0.84, -3.13]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane024.geometry}
      material={gltf.materials['Material.047']}
      position={[-57.48, 5.49, 3.06]}
      rotation={[-2.76, -0.84, -3.13]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane025.geometry}
      material={gltf.materials['Material.047']}
      position={[-50.82, -0.27, 6.34]}
      rotation={[3.09, -0.5, 3]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane029.geometry}
      material={gltf.materials['Material.047']}
      position={[-49.89, -0.23, 5.88]}
      rotation={[0.7, -1.5, 0.58]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane030.geometry}
      material={gltf.materials['Material.047']}
      position={[-49.44, -0.22, 4.85]}
      rotation={[0.07, -0.81, -0.07]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane031.geometry}
      material={gltf.materials['Material.047']}
      position={[-46.77, -0.27, -5.96]}
      rotation={[2.81, -1.43, 2.69]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane032.geometry}
      material={gltf.materials['Material.047']}
      position={[-46.58, -0.23, -6.97]}
      rotation={[0.06, -0.58, -0.09]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Plane033.geometry}
      material={gltf.materials['Material.047']}
      position={[-47.15, -0.22, -7.95]}
      rotation={[0.05, 0.13, -0.12]}
      scale={[0.47, 0.6, 1.42]}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve004.geometry}
      material={gltf.materials['Material.049']}
      position={[-56.89, 0.17, 8]}
      rotation={[0.45, -0.47, 2.95]}
      scale={12.75}
    />
    <T.Group
      position={[-54.33, 1.45, -2]}
      rotation={[Math.PI / 2, 0, -2.63]}
      scale={4}
    >
      <T.Mesh
        geometry={gltf.nodes.Curve004_1.geometry}
        material={gltf.materials['SVGMat.018']}
      />
      <T.Mesh
        geometry={gltf.nodes.Curve004_2.geometry}
        material={gltf.materials['FrontColor.003']}
      />
      <T.Mesh
        geometry={gltf.nodes.Curve004_3.geometry}
        material={gltf.materials['Material.056']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube025.geometry}
      material={gltf.materials['Material.057']}
      position={[-27.96, 4.05, -0.68]}
      rotation={[0, 1.56, 0]}
      scale={[1.5, 0.4, 0.1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Curve.geometry}
      material={gltf.materials['SVGMat.002']}
      position={[-27.8, 4.03, -0.68]}
      rotation={[Math.PI / 2, 0, -1.56]}
      scale={2.74}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube001.geometry}
      material={gltf.nodes.Cube001.material}
      position={[0, 0.3, 0]}
      scale={0.29}
    />
    <T.Mesh
      geometry={gltf.nodes.Sui.geometry}
      material={gltf.materials.SVGMat}
      position={[-0.03, 1.92, 0]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={9.21}
    />
    <T.Group
      position={[0, 15, 13.45]}
      scale={[2, 1, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube001_1.geometry}
        material={gltf.materials['Material.015']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube001_2.geometry}
        material={gltf.materials.SVGMat}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube001_3.geometry}
        material={gltf.materials['Material.015']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Ground.geometry}
      material={gltf.materials['Material.001']}
      position={[-1.74, -0.51, -0.83]}
      scale={[10, 5, 10]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube.geometry}
      material={gltf.nodes.Cube.material}
      position={[-14.16, 2.34, -9.84]}
      rotation={[0, 0.84, 0]}
      scale={[2, 1, 2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube002.geometry}
      material={gltf.nodes.Cube002.material}
      position={[18.72, 2.34, 14.98]}
      rotation={[Math.PI, -0.8, Math.PI]}
      scale={[2, 1, 2]}
    />
    <T.Group position={[-10.04, 3.05, -11.55]}>
      <T.Mesh
        geometry={gltf.nodes.Cylinder001_1.geometry}
        material={gltf.materials['Material.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder001_2.geometry}
        material={gltf.materials['Material.003']}
      />
    </T.Group>
    <T.Group
      position={[14.65, 3.05, -6.13]}
      rotation={[Math.PI, -1.48, Math.PI]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder004_1.geometry}
        material={gltf.materials['Material.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder004_2.geometry}
        material={gltf.materials['Material.003']}
      />
    </T.Group>
    <T.Group
      position={[-10.8, 1.54, -11.68]}
      rotation={[0, 0, 0.46]}
      scale={0.58}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder006_1.geometry}
        material={gltf.materials['Material.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder006_2.geometry}
        material={gltf.materials['Material.003']}
      />
    </T.Group>
    <T.Group
      position={[-21.26, 3.02, 12.3]}
      rotation={[-2.85, -0.1, -2.8]}
      scale={[0.24, 0.47, 0.94]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane030_1.geometry}
        material={gltf.materials['Material.003']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane030_2.geometry}
        material={gltf.materials['Material.001']}
      />
    </T.Group>
    <T.Group
      position={[19, 3.02, 9.82]}
      rotation={[-0.3, 0.26, 0.38]}
      scale={[0.24, 0.47, 0.94]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane031_1.geometry}
        material={gltf.materials['Material.003']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane031_2.geometry}
        material={gltf.materials['Material.001']}
      />
    </T.Group>
    <T.Group
      position={[-9.14, 1.62, -12.13]}
      rotation={[3.01, 1.01, -2.49]}
      scale={[0.14, 0.27, 0.54]}
    >
      <T.Mesh
        geometry={gltf.nodes.Plane033_1.geometry}
        material={gltf.materials['Material.003']}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane033_2.geometry}
        material={gltf.materials['Material.001']}
      />
    </T.Group>
    <T.Group
      position={[-17.47, 2.49, -21.91]}
      rotation={[0, -0.29, 0]}
      scale={3.16}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder003_1.geometry}
        material={gltf.materials['Material.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder003_2.geometry}
        material={gltf.materials['Material.008']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder003_3.geometry}
        material={gltf.materials['Material.014']}
      />
    </T.Group>
    <T.Group
      position={[-23.79, 10.06, -21.13]}
      rotation={[-3.09, 0.72, -2.65]}
      scale={[0.16, 0.31, 0.63]}
    >
      <T.Mesh
        geometry={gltf.nodes.PalmStation004.geometry}
        material={gltf.materials['Material.003']}
      />
      <T.Mesh
        geometry={gltf.nodes.PalmStation004_1.geometry}
        material={gltf.materials['Material.001']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube003.geometry}
      material={gltf.materials['Material.016']}
      position={[-21.29, -0.06, 16.79]}
      rotation={[0, 0.08, 0]}
      scale={0.6}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube005.geometry}
      material={gltf.materials['Material.016']}
      position={[-16.52, -0.04, 17.15]}
      rotation={[-0.4, -0.71, 0.89]}
      scale={0.19}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube006.geometry}
      material={gltf.materials['Material.016']}
      position={[-18.26, 0.12, 15.21]}
      rotation={[Math.PI, -1.33, Math.PI]}
      scale={0.22}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube007.geometry}
      material={gltf.materials['Material.016']}
      position={[-18.69, -0.04, 15.1]}
      rotation={[-2.79, -0.55, -1.79]}
      scale={0.19}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube008.geometry}
      material={gltf.materials['Material.016']}
      position={[-16.59, -0.03, 17.61]}
      rotation={[-2.79, -0.55, -1.79]}
      scale={0.13}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube009.geometry}
      material={gltf.materials['Material.017']}
      position={[-21.58, -0.26, 12.82]}
      rotation={[0, -1.11, 0]}
      scale={0.6}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube010.geometry}
      material={gltf.materials['Material.017']}
      position={[-20.62, -0.5, 12.21]}
      rotation={[-0.22, -1.1, -0.25]}
      scale={-0.87}
    />
    <T.Group
      position={[0, 0.94, 33.04]}
      scale={[0.4, 1.01, 0.4]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube003_1.geometry}
        material={gltf.materials['Material.018']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_2.geometry}
        material={gltf.materials['Material.030']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_3.geometry}
        material={gltf.materials['Material.018']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube003_4.geometry}
        material={gltf.materials['Material.018']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube011.geometry}
      material={gltf.materials['Material.005']}
      position={[-1.77, 0.6, -1.02]}
      rotation={[0, 1.57, 0]}
      scale={[0.3, 0.3, 0.6]}
    />
    <T.Group
      position={[-29, 1.16, 24.37]}
      rotation={[0, -0.91, 0]}
      scale={[0.2, 0.5, 0.2]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube025_1.geometry}
        material={gltf.materials['Material.018']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube025_2.geometry}
        material={gltf.materials['Material.030']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube025_3.geometry}
        material={gltf.materials['Material.018']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube025_4.geometry}
        material={gltf.materials['Material.018']}
      />
    </T.Group>
    <T.Group
      position={[-18.64, 2.15, 17.16]}
      rotation={[Math.PI / 2, 0, -2.22]}
    >
      <T.Mesh
        geometry={gltf.nodes.Untitled001_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Untitled001_2.geometry}
        material={gltf.materials['Material.036']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Cube013.geometry}
      material={gltf.materials['Material.030']}
      position={[-37.81, -0.07, -0.29]}
      rotation={[0, -Math.PI / 2, 0]}
      scale={[0.2, 0.5, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube014.geometry}
      material={gltf.materials['Material.048']}
      position={[-38.04, 0.81, 0.53]}
      scale={[0.2, 2, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube018.geometry}
      material={gltf.materials['Material.048']}
      position={[-43.28, 1, -1.44]}
      scale={[0.2, 2, 0.2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Cube021.geometry}
      material={gltf.materials['Material.039']}
      position={[-17.97, 6.96, -22.48]}
      scale={0.2}
    />
    <T.Group
      position={[-16.62, 10.51, -22.48]}
      rotation={[0, 0, 0.09]}
      scale={[0.2, 2.5, 0.2]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cube040.geometry}
        material={gltf.materials['Material.015']}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube040_1.geometry}
        material={gltf.materials['Material.037']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Base001.geometry}
      material={gltf.materials['Material.022']}
      position={[-17.16, 10.5, -22.42]}
      rotation={[0, 0, 0.37]}
      scale={[0.57, 1.42, 0.28]}
    />
    <T.Mesh
      geometry={gltf.nodes.Untitled002.geometry}
      material={gltf.materials.FrontColor}
      position={[19.28, 1.55, 1.36]}
      rotation={[Math.PI / 2, 0, -Math.PI]}
    />
    <T.Group
      position={[29.68, 2.4, -22.64]}
      rotation={[Math.PI / 2, 0, -0.56]}
    >
      <T.Mesh
        geometry={gltf.nodes.market012.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.market012_1.geometry}
        material={gltf.materials['Material.036']}
      />
    </T.Group>
    <T.Group
      position={[-0.5, 1.5, -12.22]}
      rotation={[Math.PI / 2, 0, 0]}
    >
      <T.Mesh
        geometry={gltf.nodes.referencies001_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.referencies001_2.geometry}
        material={gltf.materials['Material.036']}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
