<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\spacestation.glb -T --draco /draco/
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/spacestation-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Island.geometry}
      material={gltf.materials['Material.001']}
      position={[52.45, -0.51, -40.95]}
      rotation={[0, -0.07, 0]}
      scale={5}
    />
    <T.Group
      position={[56.45, 2.51, -41.68]}
      rotation={[Math.PI / 2, 0, 0]}
    >
      <T.Mesh
        geometry={gltf.nodes.Station_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Station_2.geometry}
        material={gltf.materials['Material.006']}
      />
    </T.Group>
    <T.Group
      position={[52.7, 0.66, -46.28]}
      rotation={[Math.PI / 2, 0, 0]}
    >
      <T.Mesh
        geometry={gltf.nodes.Trash_1.geometry}
        material={gltf.materials.FrontColor}
      />
      <T.Mesh
        geometry={gltf.nodes.Trash_2.geometry}
        material={gltf.materials['Material.009']}
      />
      <T.Mesh
        geometry={gltf.nodes.Trash_3.geometry}
        material={gltf.materials['Material.010']}
      />
    </T.Group>
    <T.Group
      position={[51.36, 1.5, -38.68]}
      rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      scale={7}
    >
      <T.Mesh
        geometry={gltf.nodes.Sui001_1.geometry}
        material={gltf.materials['SVGMat.001']}
      />
      <T.Mesh
        geometry={gltf.nodes.Sui001_2.geometry}
        material={gltf.materials['Material.012']}
      />
    </T.Group>
    <T.Group
      position={[48, 5.01, -45.8]}
      scale={[2, 5, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.Base_1.geometry}
        material={gltf.materials['Material.023']}
      />
      <T.Mesh
        geometry={gltf.nodes.Base_2.geometry}
        material={gltf.materials['Material.022']}
      />
    </T.Group>
    <T.Group
      position={[47.98, 5.99, -41.01]}
      scale={[1, 5, 1]}
    >
      <T.Mesh
        geometry={gltf.nodes.SpaceShip005.geometry}
        material={gltf.materials['Material.020']}
      />
      <T.Mesh
        geometry={gltf.nodes.SpaceShip005_1.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.SpaceShip005_2.geometry}
        material={gltf.materials['Material.021']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.rocks.geometry}
      material={gltf.materials['Material.017']}
      position={[41.37, -0.53, -41.51]}
      rotation={[-3.04, -0.03, 3.1]}
      scale={-0.87}
    />
    <T.Group
      position={[40.52, 3.08, -39.99]}
      rotation={[-3.1, 0.31, -2.63]}
      scale={[0.16, 0.31, 0.63]}
    >
      <T.Mesh
        geometry={gltf.nodes.PalmStation001.geometry}
        material={gltf.materials['Material.003']}
      />
      <T.Mesh
        geometry={gltf.nodes.PalmStation001_1.geometry}
        material={gltf.materials['Material.001']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Space_Station_Text.geometry}
      material={gltf.materials.Material}
      position={[55.78, 4.49, -37.78]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={7.66}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
